# Generated by Django 4.0.5 on 2022-06-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Surname')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('last_visit', models.DateTimeField(auto_now=True, null=True, verbose_name='Last visit')),
                ('visit_counts', models.IntegerField(blank=True, default=1, null=True, verbose_name='Visits count')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Last Image')),
                ('face_encodings', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
                'ordering': ['pk'],
            },
        ),
    ]
