# Generated by Django 4.0.5 on 2022-06-29 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='last_visit',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='visit_counts',
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last visit')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.personal')),
            ],
        ),
    ]
